services:
  # PostgreSQL
  db:
    image: postgres:16-alpine
    container_name: pservicios_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: pservicios
      POSTGRES_USER: pservicios_user
      POSTGRES_PASSWORD: pservicios_secret
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pservicios_user -d pservicios"]
      interval: 5s
      timeout: 5s
      retries: 10

  # Backend Laravel
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: pservicios_backend
    restart: unless-stopped
    ports:
      - "8080:8000"
    environment:
      APP_NAME: PServicios
      APP_ENV: local
      APP_KEY: base64:xR3TbPNBfz4mGU5MhKtp3HKDO+jMnaSj6UEahGkAjQo=
      APP_DEBUG: "true"
      APP_URL: http://localhost:8000
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: pservicios
      DB_USERNAME: pservicios_user
      DB_PASSWORD: pservicios_secret
    depends_on:
      db:
        condition: service_healthy

  # Frontend Expo Web
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: pservicios_frontend
    restart: unless-stopped
    ports:
      - "8081:8081"
    depends_on:
      - backend

volumes:
  pgdata:
